// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *wohnung → Wohnung*
 */
export interface WohnungDocumentDataWohnungItem {
  /**
   * id field in *wohnung → Wohnung*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wohnung.wohnung[].apt_id
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  apt_id: prismic.KeyTextField;

  /**
   * Wohnungsnummer field in *wohnung → Wohnung*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wohnung.wohnung[].number
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  number: prismic.KeyTextField;

  /**
   * Zimmer field in *wohnung → Wohnung*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wohnung.wohnung[].rooms
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  rooms: prismic.KeyTextField;

  /**
   * Status field in *wohnung → Wohnung*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: wohnung.wohnung[].status
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  status: prismic.SelectField<"frei" | "reserviert" | "verkauft">;

  /**
   * Fläche field in *wohnung → Wohnung*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wohnung.wohnung[].space
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  space: prismic.KeyTextField;

  /**
   * Geschoss field in *wohnung → Wohnung*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: wohnung.wohnung[].floor
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  floor: prismic.SelectField<
    "1-Erdgeschoss" | "2-Obergeschoss" | "3-Attikagechoss" | "0-Gartengeschoss"
  >;

  /**
   * Preis field in *wohnung → Wohnung*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: wohnung.wohnung[].price
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  price: prismic.KeyTextField;
}

/**
 * Content for wohnung documents
 */
interface WohnungDocumentData {
  /**
   * Wohnung field in *wohnung*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: wohnung.wohnung[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  wohnung: prismic.GroupField<Simplify<WohnungDocumentDataWohnungItem>>;
}

/**
 * wohnung document from Prismic
 *
 * - **API ID**: `wohnung`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WohnungDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<WohnungDocumentData>,
    "wohnung",
    Lang
  >;

export type AllDocumentTypes = WohnungDocument;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      WohnungDocument,
      WohnungDocumentData,
      WohnungDocumentDataWohnungItem,
      AllDocumentTypes,
    };
  }
}
